viper_web/urls.py
# -*- coding: utf-8 -*-
# This file is part of Viper - https://github.com/viper-framework/viper
# See the file 'LICENSE' for copying permission.

from django.urls import include, re_path
from django.contrib import admin

from viper.core.config import __config__

cfg = __config__


urlpatterns = [
    re_path(r'^', include('viper_web.viperweb.urls')),
    re_path(r'^', include('favicon.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^api/', include('viper_web.viperapi.urls')),
]

viper_web/viperapi/urls.py
# -*- coding: utf-8 -*-
# This file is part of Viper - https://github.com/viper-framework/viper
# See the file 'LICENSE' for copying permission.

from django.urls import include, re_path
from django.views.generic import RedirectView
from rest_framework_nested import routers
from rest_framework_swagger.views import get_swagger_view

from . import views

app_name = 'viperapi_v3'

router = routers.DefaultRouter()
# project router
router.register(r'project', views.ProjectViewSet, basename="project")

# 1. level nested router: project/<pk>
project_router = routers.NestedSimpleRouter(router, r'project', lookup='project')

project_router.register(r'malware', views.MalwareViewSet, basename="malware")
project_router.register(r'tag', views.TagViewSet, basename="tag")
project_router.register(r'note', views.NoteViewSet, basename="note")
project_router.register(r'analysis', views.AnalysisViewSet, basename="analysis")

# 2. level nested router: project/<pk>/malware/<pk>
malware_router = routers.NestedSimpleRouter(project_router, r'malware', lookup='malware')

# 3. level nested for malware tags
malware_router.register(r'analysis', views.MalwareAnalysisViewSet, basename='malware-analysis')
malware_router.register(r'note', views.MalwareNoteViewSet, basename='malware-note')
malware_router.register(r'tag', views.MalwareTagViewSet, basename='malware-tag')

schema_view = get_swagger_view(title='Viper API v3')

urlpatterns = [
    # Main API route -> Redirect /api/ to /api/v3/project/
    re_path(r'^$', RedirectView.as_view(pattern_name='viperapi_v3:project-list'), name='redirect-to-api-v3'),

    # Extractors
    re_path(r'^v3/extractor/$', views.ExtractorAPIView.as_view(), name="extractor-list"),
    re_path(r'^v3/compressor/$', views.CompressorAPIView.as_view(), name="compressor-list"),
    re_path(r'^v3/module/$', views.ModuleAPIView.as_view(), name="module-list"),

    re_path(r'^v3/', include(router.urls)),
    re_path(r'^v3/', include(project_router.urls)),
    re_path(r'^v3/', include(malware_router.urls)),

    # Test Pages
    re_path(r'^v3/test/$', views.test, name='test'),
    re_path(r'^v3/test-auth/$', views.test_authenticated, name='test-auth'),

    # Docs (using Swagger)
    re_path(r'^v3/docs/', schema_view, name='api-docs'),
]

web/urls.py
# -*- coding: utf-8 -*-
# This file is part of Viper - https://github.com/viper-framework/viper
# See the file 'LICENSE' for copying permission.

from django.conf.urls import include, url
from django.contrib import admin

from viper.core.config import __config__

cfg = __config__


urlpatterns = [
    url(r'^', include('viper.web.viperweb.urls')),
    url(r'^', include('favicon.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('viper.web.viperapi.urls')),
]

web/viperweb/urls.py
# This file is part of Viper - https://github.com/viper-framework/viper
# See the file 'LICENSE' for copying permission.

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views
from .forms import MyAuthenticationForm


urlpatterns = [
    # login/logout (accounts)
    url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='viperweb/user_login.html',
                                                           authentication_form=MyAuthenticationForm), name='login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(template_name='viperweb/logged_out.html'), name='logout'),

    # Main Page
    url(r'^$', views.MainPageView.as_view(), name='main_page'),
    url(r'^project/(?P<project>[^/]+)/$', views.MainPageView.as_view(), name='main-page-project'),  # Project Page (Main view)

    url(r'^about/', views.AboutView.as_view(), name='about'),
    url(r'^changelog/', views.ChangelogView.as_view(), name='changelog'),
    url(r'^config/$', views.ConfigView.as_view(), name='config-file'),
    url(r'^create/$', views.CreateProjectView.as_view(), name='create-project'),

    url(r'^project/default/cli/$', views.CliView.as_view(), name='cli-default'),
    url(r'^project/(?P<project>[^/]+)/cli/$', views.CliView.as_view(), name='cli'),

    url(r'^project/(?P<project>[^/]+)/file/(?P<sha256>[^/]+)/$', views.FileView.as_view(), name='file-view'),  # File Page
    url(r'^project/(?P<project>[^/]+)/file/$', views.FileView.as_view(), name='file-list'),  # File List

    url(r'^project/(?P<project>[^/]+)/file/(?P<sha256>[^/]+)/cuckoo/$', views.CuckooCheckOrSubmitView.as_view(), name='file-cuckoo-submit'),

    url(r'^project/(?P<project>[^/]+)/hex/$', views.HexView.as_view(), name='hex-view'),  # Hex View
    url(r'^project/(?P<project>[^/]+)/module/$', views.RunModuleView.as_view(), name='run-module'),  # Run Module Ajax
    url(r'^project/(?P<project>[^/]+)/addchild/$', views.AddParentView.as_view(), name='add-parent'),
    url(r'^project/(?P<project>[^/]+)/deletechild/$', views.DeleteParentView.as_view(), name='delete-parent'),


    url(r'^search/$', views.SearchFileView.as_view(), name='search-file'),  # Search
    url(r'^urldownload/', views.UrlDownloadView.as_view(), name='url-download'),  # Download from URL
    url(r'^yara/$', views.YaraRulesView.as_view(), name='yara-rules'),  # Yara


    url(r'^virustotal/$', views.VtDownloadView.as_view(), name='vt-download'),  # Download form Virustotal

]

viper_web/viperweb/models.py
# from django.db import models

# Create your models here.

viper_web/viperweb/forms.py
# from django import forms
# from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm


class MyAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(MyAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = u'Username'
        self.fields['password'].widget.attrs['placeholder'] = u'Password'

viper_web/viperapi/views.py
# -*- coding: utf-8 -*-
# This file is part of Viper - https://github.com/viper-framework/viper
# See the file 'LICENSE' for copying permission.

# Standard Imports
import os
from functools import wraps
import shutil
import tempfile

# Logging
import logging

# Django Imports
from django.shortcuts import HttpResponse
from django.utils.encoding import force_text
from django.core.files import File as DjangoFile

# DRF
from rest_framework import viewsets
from rest_framework import status
from rest_framework.parsers import FormParser, MultiPartParser, FileUploadParser
from rest_framework.compat import coreapi, coreschema
from rest_framework.filters import SearchFilter, OrderingFilter, BaseFilterBackend
from rest_framework.generics import ListAPIView
from rest_framework.mixins import ListModelMixin, CreateModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import api_view, action, permission_classes
from rest_framework.exceptions import NotFound, ValidationError
from rest_framework.settings import api_settings

# SQL Alchemy
from sqlalchemy import or_
from sqlalchemy.orm import Session
from sqlalchemy.orm import subqueryload

# Serializers
from .serializers import ObjectSerializer
from .serializers import AnalysisSerializer, NoteSerializer, TagSerializer
from .serializers import MalwareAnalysisSerializer, MalwareNoteSerializer, MalwareTagSerializer
from .serializers import ProjectSerializer, ProjectListSerializer
from .serializers import PassSerializer
from .serializers import MalwareDownloadSerializer, MalwareUploadSerializer

# Viper imports
from viper.core.plugins import __modules__
from viper.core.project import __project__
from viper.core.project import get_project_list
from viper.common.objects import File
from viper.common.autorun import autorun_module
from viper.core.storage import store_sample, get_sample_path
from viper.core.database import Database, Malware, Tag, Note, Analysis
from viper.core.archiver import Compressor, Extractor
from viper.core.config import __config__

try:
    from scandir import walk  # noqa
except ImportError:
    from os import walk  # noqa

log = logging.getLogger("viper_web")
cfg = __config__

################
# API v3 (DRF) #
################


class SingleTermMultiFieldStartsWithSearchFilter(SearchFilter):
    def filter_queryset(self, request, queryset, view):
        search_fields = getattr(view, 'search_fields', None)
        search_terms = self.get_search_terms(request)

        if not search_fields or not search_terms:
            return queryset

        log.debug("Searching for \"{}\" in: {}".format(search_terms[0], search_fields))
        return queryset.filter(or_(*[(getattr(view.model, x).startswith(search_terms[0])) for x in search_fields]))


class FieldsFilter(BaseFilterBackend):
    def filter_queryset(self, request, queryset, view):
        return queryset

    def get_schema_fields(self, views):
        return [
            coreapi.Field(
                name="fields",
                required=False,
                location='query',
                schema=coreschema.String(
                    title='Cursor',
                    description=force_text("List of fields (comma separated) to be displayed. "
                                           "If empty all are shown. Can include _set fields.")
                )
            )
        ]


def get_project_open_db():
    """decorator: get project name from kwargs and open project database"""
    def my_decorator(func):
        @wraps(func)
        def func_wrapper(viewset, *args, **kwargs):
            log.debug("running decorator: get_project_open_db - called by: {}".format(viewset))

            project = viewset.kwargs.get(viewset.lookup_field_project, None)
            if project == 'default':
                __project__.open(project)
                db = Database()
            elif project in get_project_list():
                log.debug("setting project to: {}".format(project))
                __project__.open(project)
                db = Database()
            else:
                db = None

            if not db:
                error = {"error": {"code": "NotFound", "message": "Project not found: {}".format(project)}}
                log.error(error)
                raise NotFound(detail=error)

            return func(viewset, project=project, db=db, *args, **kwargs)
        return func_wrapper
    return my_decorator


class ExtractorAPIView(ListAPIView):
    """List available Archive Extractors"""
    queryset = [x.summary for (key, x) in Extractor().extractors.items()]
    serializer_class = PassSerializer


class CompressorAPIView(ListAPIView):
    """List available Archive Compressors"""
    queryset = [x.summary for (key, x) in Compressor().compressors.items()]
    serializer_class = PassSerializer


class ModuleAPIView(ListAPIView):
    """List available Modules"""
    queryset = [{"name": key, "description": value["description"]} for key, value in __modules__.items()]
    serializer_class = PassSerializer


class ViperGenericViewSet(ListModelMixin, RetrieveModelMixin, viewsets.GenericViewSet):
    """Generic View Set that implements common things that are required for accessing the SQLAlchemy models"""
    model = None
    serializer_class = None
    permission_classes = (IsAuthenticated,)

    lookup_field = 'id'
    lookup_field_project = 'project_name'

    @get_project_open_db()
    def get_object(self, project=None, db=None, *args, **kwargs):

        session = db.Session()
        obj = session.query(self.model).get(self.kwargs[self.lookup_field])
        if not obj:
            error = {"error": {"code": "NotFound",
                               "message": "{} not found ({}: {})".format(self.model.__name__,
                                                                         self.lookup_field,
                                                                         self.kwargs[self.lookup_field])}}
            raise NotFound(detail=error)
        return obj

    @get_project_open_db()
    def get_queryset(self, project=None, db=None, *args, **kwargs):

        session = db.Session()
        queryset = session.query(self.model)
        return queryset

    def get_serializer_context(self, *args, **kwargs):
        project = self.kwargs.get(self.lookup_field_project, None)
        context = dict()
        context["request"] = self.request
        context["project"] = project
        return context


class ViperGenericMalwareViewSet(ViperGenericViewSet):
    """Special customization for SQLAlchemy models that are directly tied to a malware instance (Analysis, Note, Tag)"""
    malware_relationship_field = None

    @get_project_open_db()
    def get_queryset(self, project=None, db=None, *args, **kwargs):
        malware_sha256 = self.kwargs["malware_sha256"]

        if malware_sha256:
            session = db.Session()
            malware = session.query(Malware).filter(Malware.sha256 == malware_sha256).one_or_none()

            if not malware:
                error = {"error": {"code": "NotFound",
                                   "message": "Malware not found: {} (Project: {})".format(malware_sha256, project)}}
                raise NotFound(detail=error)

            session = db.Session()

            malware = session.query(Malware) \
                .options(subqueryload(Malware.tag)) \
                .options(subqueryload(Malware.analysis)) \
                .options(subqueryload(Malware.note)).filter(Malware.sha256 == malware_sha256).one_or_none()

            queryset = getattr(malware, self.malware_relationship_field)

        else:
            session = db.Session()
            queryset = session.query(self.model)

        return queryset


class ProjectViewSet(ViperGenericViewSet, CreateModelMixin):
    """List and Retrieve Projects"""
    model = None
    serializer_class = ProjectSerializer  # list() overrides this

    lookup_field = 'name'  # this make sure that the URL keyword is project_name
    lookup_field_project = lookup_field

    @get_project_open_db()
    def get_object(self, project=None, db=None, *args, **kwargs):
        return project

    # @get_project_open_db()
    def get_queryset(self, project=None, db=None, *args, **kwargs):
        projects = get_project_list()
        if not next((i for i in projects if i == "default"), None):
            projects.append("default")  # make sure "default" is part of list of projects
        return projects

    def list(self, request, *args, **kwargs):
        """List all Projects"""
        self.serializer_class = ProjectListSerializer
        return super(ProjectViewSet, self).list(request, *args, **kwargs)

    def retrieve(self, request, *args, **kwargs):
        """Retrieve a Project"""
        return super(ProjectViewSet, self).retrieve(request, *args, **kwargs)

    def create(self, request, project=None, db=None, *args, **kwargs):
        """Create a new Project"""
        # kwargs provided by URLs/Routers: -

        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        if serializer.validated_data['name'] in get_project_list():
            # exists already
            # return Response(data=serializer.validated_data, status=status.HTTP_200_OK)
            error = {"error": {"code": "ExistsAlready",
                               "message": "Project exists already: {}".format(serializer.validated_data['name'])}}
            raise ValidationError(detail=error)

        new_project_new = serializer.validated_data['name']

        __project__.open(new_project_new)

        serializer_new = self.get_serializer(new_project_new)
        headers = self.get_success_headers(serializer_new.data)

        return Response(data=serializer_new.data, status=status.HTTP_201_CREATED, headers=headers)

viper_web/viperweb/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="Viper Malware Analysis">
    <meta name="keywords" content="viper,malware,yara">

    <title>Viper - {% block title %}{% endblock %}</title>

    {% load static %}

    <link rel="stylesheet" href="{% static "viperweb/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "viperweb/css/dataTables.bootstrap4.min.css" %}"/>
    <link rel="stylesheet" href="{% static "viperweb/css/fontawesome-all.css" %}">
    <link rel="stylesheet" href="{% static "viperweb/css/viper.css" %}"/>
</head>

<body role="document">
<!-- Start Navbar -->
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="#"><img src="{% static "viperweb/images/viper_inverse.png" %}" width="92" height="25" alt="Viper"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    {% if user.is_authenticated %}

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownProjects" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Projects
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownProjects">
                        <a class="dropdown-item" href="/"><i class="fas fa-angle-right fa-fw mr-1" style="color: black"></i>default</a>
                        <div class="dropdown-divider"></div>
                        {% for project in projects %}
                            {% if not project == "default" %}
                                <a class="dropdown-item" href="{% url "main-page-project" project=project %}"><i class="fas fa-angle-right fa-fw mr-1" style="color: black"></i>{{ project }}</a>
                            {% endif %}
                        {% endfor %}
                        <div class="dropdown-divider"></div>

                        <form class="form-inline my-lg-0" action="{% url "create-project" %}" enctype="multipart/form-data" method="post">
                            <input class="form-control mx-2" type="text" name="project" placeholder="switch to/create new">
                            {% csrf_token %}
                        </form>

                    </div>
                </li>
                <li class="nav-link">
                    <a href="https://cuckoo.scouting4u.co.uk:2443" target="_blank">CyberChef</a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url "yara-rules" %}">Yara Rules</a>
                </li>

                {% if project %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cli' project=project %}">CLI</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cli-default' %}">CLI</a>
                    </li>
                {% endif %} -->

            </ul>

            <form id="search_form_navbar" class="form-inline my-2 my-lg-0" role="form" enctype="multipart/form-data" action="{% url "search-file" %}" method="POST">
                <input class="form-control mr-sm-2" type="search" name="term" id="term" placeholder="Search in all Projects">

                <label for="search_options" hidden></label>
                <select class="form-control mx-0 my-2 my-sm-0" id="search_options" name="key">
                    <option value="name">Name</option>
                    <option value="type">Type</option>
                    <option value="mime">Mime</option>
                    <option value="md5">MD5</option>
                    <option value="sha256">SHA256</option>
                    <option value="tag">Tag</option>
                    <option value="note">Note</option>
                </select>

                <button class="btn mx-2 my-2 my-sm-0" type="submit">Search</button>
                <input type="hidden" name="search-project-radio" value="search-all-projects"/>
                {% csrf_token %}
            </form>

            <ul class="navbar-nav ml-auto">

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMoreAuthenticated" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        More
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMoreAuthenticated">
                        <a class="dropdown-item" href="{% url "admin:index" %}"><i class="fas fa-cogs fa-fw mx-1" style="color: black"></i> Admin</a>
                        <div class="dropdown-divider"></div>

                        <a class="dropdown-item" href="#" rel="noreferrer noopener">
                            <i class="fas fa-book fa-fw mx-1" style="color: black"></i>Documentation</a>
                        <a class="dropdown-item" href="#" rel="noreferrer noopener">
                            <i class="fab fa-github fa-fw mx-1" style="color: black"></i>Issues</a>
                        <div class="dropdown-divider"></div>

                        <a class="dropdown-item" href="{% url "viperapi_v3:api-root" %}"><i class="fas fa-code fa-fw mx-1" style="color: black"></i>API</a>
                        <a class="dropdown-item" href="{% url "viperapi_v3:api-docs" %}"><i class="fas fa-file-code fa-fw mx-1" style="color: black"></i>API Docs</a>

                        <div class="dropdown-divider"></div>

                        <a class="dropdown-item" href="{% url "about" %}"><i class="fas fa-info-circle fa-fw mx-1" style="color: black"></i>About</a>
                        {#                        <a class="dropdown-item" href="{% url "changelog" %}">Changelog (TODO!)</a>#}
                        {#                        <a class="dropdown-item" href="{% url "config-file" %}">Config (TODO!)</a>#}
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url "logout" %}" title="Logout">Logout ({{ user }}) <i class="fas fa-sign-out-alt"></i>  </a>
                </li>

            </ul>
        </div>

    {% else %}

        <ul class="navbar-nav ml-auto">

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMoreUnauthenticated" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    More
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMoreUnauthenticated">
                    <a class="dropdown-item" href="#" rel="noreferrer noopener">
                        <i class="fas fa-book fa-fw mx-1" style="color: black"></i>Documentation</a>
                    <a class="dropdown-item" href="#" rel="noreferrer noopener">
                        <i class="fab fa-github fa-fw mx-1" style="color: black"></i>Issues</a>
                    <div class="dropdown-divider"></div>

                    {#                        <a class="dropdown-item" href="{% url "changelog" %}">Changelog (TODO!)</a>#}
                    <a class="dropdown-item" href="{% url "about" %}"><i class="fas fa-info-circle fa-fw mx-1" style="color: black"></i>About</a>

                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "login" %}" title="Login">Login <i class="fas fa-sign-in-alt"></i></a>
            </li>
        </ul>

    {% endif %}
</nav>
<!-- End Navbar -->

<div class="container-fluid">

    <!-- Bootstrap display flashed messages -->
    <!-- possible values: alert alert-[info|success|warning|danger] -->
    <!--
        from django.contrib import messages
        messages.info(request, "info: Invalid credentials!")
        messages.success(request, "success: Invalid credentials!")
        messages.warning(request, "warning: Invalid credentials!")
        messages.error(request, "error: Invalid credentials!")
        # Debug messages ignored by default settings.py: MESSAGE_LEVEL = message_constants.DEBUG
        messages.debug(request, "debug: Invalid credentials!")
    -->

    {% if messages %}
        <div class="page-header">
            {% for message in messages %}
                {% if message.tags == "error" %}
                    <div class="alert alert-danger text-center">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>Error: </strong> {{ message }}.
                    </div>
                {% elif message.tags %}
                    <div class="alert alert-{{ message.tags }} text-center">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>{{ message.tags }}:</strong> {{ message }}.
                    </div>
                {% else %}
                    <div class="alert alert-info text-center">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>Info!</strong> {{ message }}.
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}

    {% block content %}{% endblock %}
</div>

<br>
<footer class="footer">
    <div class="container" align="center">
            <span class="text-muted align-left"><a href="#" rel="noreferrer noopener">Viper-Framework</a> |
                Source Code on <a href="#" rel="noreferrer noopener" title="Github"><i class="fab fa-github mx-1" style="color: black"></i></a></span>
    </div>
</footer>

<!-- include libraries(jQuery, Bootstrap4, BS Fileview, Spinner, JS Cookie) -->
<script type="text/javascript" src="{% static 'viperweb/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'viperweb/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'viperweb/js/bootstrap-filestyle.min.js' %}"></script>
<script type="text/javascript" src="{% static 'viperweb/js/spin.min.js' %}"></script>
<script type="text/javascript" src="{% static "viperweb/js/js.cookie.js" %}"></script>

<!-- Viper JavaScript -->
<script type="text/javascript" src="{% static 'viperweb/js/viper_dropdown.js' %}"></script>
<script type="text/javascript" src="{% static 'viperweb/js/viper_ajax_submit.js' %}"></script>

<!-- JavaScript block per template page -->
{% block js %}
{% endblock %}

</body>
</html>